-- Engelsk katalogindhold og events fra det gamle Lovable-site.
--
-- De tre kataloger fandtes allerede på dansk; her kommer de engelske rækker
-- til, sammen med en ny events-tabel i begge sprog. Rækkerne er idempotente,
-- så migrationen kan køres igen uden dubletter.

-- Ressourcerne kan være på et andet sprog end den side, de vises på: en dansk
-- podcast optræder også i det engelske katalog. Kolonnen gør det muligt at
-- mærke det i stedet for at skjule indholdet.
alter table public.resources
  add column if not exists content_language text not null default 'da';

do $$ begin
  alter table public.resources
    add constraint resources_content_language_check check (content_language in ('da', 'en'));
exception when duplicate_object then null; end $$;

do $$ begin
  create type public.catalog_event_location as enum ('fysisk', 'online', 'hybrid');
exception when duplicate_object then null; end $$;

create table if not exists public.events (
  id uuid primary key default gen_random_uuid(),
  slug text not null,
  title text not null,
  description text not null default '',
  event_date timestamptz not null,
  time_start text,
  time_end text,
  location_type public.catalog_event_location not null default 'fysisk',
  location_name text,
  registration_url text,
  organizer text,
  price text,
  published boolean not null default false,
  locale public.catalog_locale not null default 'da',
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (slug, locale)
);

create index if not exists events_published_idx on public.events (locale, published, event_date);

drop trigger if exists events_touch_updated_at on public.events;
create trigger events_touch_updated_at before update on public.events
  for each row execute function public.touch_updated_at();

alter table public.events enable row level security;

drop policy if exists events_public_read on public.events;
create policy events_public_read on public.events
  for select to anon, authenticated using (published);

drop policy if exists events_manager_read on public.events;
create policy events_manager_read on public.events
  for select to authenticated using (private.is_content_manager());

drop policy if exists events_manager_write on public.events;
create policy events_manager_write on public.events
  for all to authenticated
  using (private.is_content_manager())
  with check (private.is_content_manager());

grant select on public.events to anon, authenticated;
grant insert, update, delete on public.events to authenticated;

-- Migreret indhold. Danske rækker, der allerede findes, springes over.
insert into public.tools (slug, name, tagline, description, icon_url, categories, badges, key_features, pricing_display, external_url, featured, published, locale, sort_order) values
  ('adobe-firefly', 'Adobe Firefly', 'Enterprise-sikker AI integreret i Creative Cloud', 'Firefly er skabt til erhvervsbrug med fokus på ophavsretlig sikkerhed. Den er integreret direkte i Photoshop, hvilket gør det muligt at redigere billeder lynhurtigt med ''Generative Fill''.', 'https://www.adobe.com/favicon.ico', array['images', 'video']::text[], array['tried_tested']::text[], array['Generative Fill: Tilføj eller fjern objekter med tekst', 'Commercial Safety: Trænet på licenseret Adobe-data']::text[], 'Inkluderet i Creative Cloud eller Gratis (begrænset)', 'https://firefly.adobe.com/', false, true, 'da', 0),
  ('bolt-new', 'Bolt.new', 'Instant webudvikling direkte i browseren', 'Bolt.new lader dig bygge, køre og deploye fulde webapplikationer direkte fra din browser via prompts. Det fjerner behovet for lokal opsætning og accelererer udviklingscyklussen markant.', 'https://bolt.new/favicon.ico', array['coding', 'automation']::text[], array['tried_tested']::text[], array['In-browser IDE: Kør koden uden at installere noget', 'StackBlitz Integration: Professionelt udviklingsmiljø']::text[], 'Freemium', 'https://bolt.new/', false, true, 'da', 1),
  ('chatgpt', 'ChatGPT', 'Verdens førende AI-assistent til erhverv og produktivitet.', 'ChatGPT er guldstandarden inden for generativ AI, der leverer massiv ROI gennem automatisering af vidensarbejde. Værktøjet fungerer som en alsidig forretningspartner, der kan analysere komplekse datasæt, generere professionelt indhold og bygge specialiserede AI-agenter (GPTs), hvilket sparer gennemsnitligt 40-60 minutter pr. medarbejder dagligt.', 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg', array['text', 'coding', 'images', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Avanceret Ræsonnering: Løser komplekse logiske opgaver med GPT-5 teknologi', 'Custom GPTs: Byg egne agenter til specifikke arbejdsgange uden kode']::text[], 'Fra $20/md (Plus) eller $25/bruger (Business)', 'https://chatgpt.com/', true, true, 'da', 2),
  ('claude-anthropic', 'Claude (Anthropic)', 'Avanceret AI med fokus på sikkerhed og nuanceret sprog', 'Claude er kendt for sin menneskelignende skrivestil og store kontekstvindue. For virksomheder leverer den høj ROI gennem præcis dokumentanalyse, kodning og kompleks opgaveløsning med færre hallucinationer end konkurrenterne.', 'https://claude.ai/favicon.ico', array['text', 'coding', 'research']::text[], array['tried_tested']::text[], array['Artifacts: Interaktivt vindue til realtids-eksekvering af kode og design', '200k Kontekstvindue: Håndtering af hele tekniske manualer eller bøger', 'Overlegen sprogforståelse og nuanceret ræsonnering']::text[], 'Gratis eller $20/md (Pro)', 'https://claude.ai/', false, true, 'da', 3),
  ('claude-design', 'Claude Design', 'Fra idé til færdigt UI-design via samtale med Claude', 'Claude Design er Anthropics nye design-værktøj, der lader dig generere komplette brugergrænseflader, prototyper og design-systemer gennem naturlig samtale med Claude. Skift mellem chat og canvas, integrér eget designsystem og eksportér til kode eller Figma. Læs vores fulde guide her: /articles/claude-design-guide', 'https://claude.ai/favicon.ico', array['other', 'coding']::text[], array['recommended', 'new']::text[], array['Chat- og canvas-tilstand til iterativt UI-design', 'Integration med eget designsystem og brand-tokens', 'Eksport til kode (HTML/CSS/React) eller Figma', 'Indbygget i Claude Pro, Max, Team og Enterprise', 'Multi-skærms prototyper og flows i én samtale']::text[], 'Inkluderet i Claude Pro (fra $20/md)', 'https://claude.ai/design', false, true, 'da', 4),
  ('elevenlabs', 'ElevenLabs', 'Verdens mest realistiske AI-stemmer', 'ElevenLabs leverer tæt på perfekte stemmer til lydbøger, videoer og spil. Deres teknologi til stemmekloning er uovertruffen og skaber stor værdi i global indholdsproduktion.', 'https://elevenlabs.io/favicon.ico', array['audio', 'video', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Voice Cloning: Klon din egen stemme på minutter', 'Speech-to-Speech: Skift stemme men bevar følelsen']::text[], 'Gratis eller $5/md (Starter)', 'https://elevenlabs.io/', true, true, 'da', 5),
  ('freepik-ai', 'Freepik AI', 'Fra lagerbilleder til AI-genereret grafik', 'Freepik har udvidet deres enorme database med AI-værktøjer. Det gør det muligt for marketingteams at generere og tilpasse grafik i én sammenhængende arbejdsgang.', 'https://www.freepik.com/favicon.ico', array['images']::text[], '{}', array['AI Image Generator: Skab billeder direkte i platformen', 'Real-time Sketch: Gør simple streger til færdig kunst']::text[], 'Gratis eller Premium abonnement', 'https://www.freepik.com/', false, true, 'da', 6),
  ('gamma', 'Gamma', 'Generer professionelle præsentationer på sekunder', 'Gamma fjerner ''den hvide side''-syndromet ved at transformere tekst eller prompts til færdige præsentationer og hjemmesider. ROI findes i den massive tidsbesparelse på layout og formatering.', 'https://gamma.app/favicon.ico', array['images', 'text']::text[], '{}', array['One-click Restyling: Skift hele præsentationens look øjeblikkeligt', 'AI-Powered Outlines: Genererer struktur og indhold automatisk']::text[], 'Gratis (Freemium) eller $8/md', 'https://gamma.app/', false, true, 'da', 7),
  ('google-ai-studio', 'Google AI Studio', 'Udviklerens sandkasse til Gemini-modeller', 'AI Studio er det ultimative værktøj til at teste og bygge med Googles nyeste modeller. Det giver adgang til de største kontekstvinduer på markedet, ideelt til analyse af enorme datamængder.', 'https://aistudio.google.com/favicon.ico', array['coding', 'text', 'automation']::text[], array['tried_tested']::text[], array['2M Context Window: Analysér gigantiske datasæt eller timevis af video', 'API Key Management: Nem overgang fra prototype til produktion']::text[], 'Gratis (inden for kvoter)', 'https://aistudio.google.com/', false, true, 'da', 8),
  ('google-gemini', 'Google Gemini', 'Multimodal intelligens integreret i Google Workspace', 'Gemini er Googles mest kapable AI, der excellerer i multimodalitet. Den skaber værdi ved at forbinde direkte til Google Workspace (Docs, Gmail, Drive), hvilket automatiserer workflows på tværs af virksomhedens eksisterende værktøjer.', 'https://www.gstatic.com/lamda/images/favicon_v1_150160d13988652c776.png', array['text', 'automation', 'images']::text[], array['recommended', 'tried_tested']::text[], array['Native Multimodalitet: Forstår tekst, billeder, video og lyd i én prompt', 'Google Workspace Integration: Hent data direkte fra Gmail og Drive', 'Ekstremt hurtig responstid']::text[], 'Gratis eller 160 kr/md (Advanced)', 'https://gemini.google.com/app', true, true, 'da', 9),
  ('google-stitch', 'Google Stitch', 'Fra vision til færdigt UI-design på sekunder', 'Google Stitch er et banebrydende AI-drevet designværktøj, der transformerer naturligt sprog eller simple skitser til high-fidelity UI-designs og produktionsklar frontend-kode. For virksomheder betyder det en markant reduktion i ''time-to-market'' for MVPs og digitale produkter, da broen mellem idé, design og kode automatiseres gennem Googles Gemini-modeller.', 'https://stitch.withgoogle.com/static/favicon.png', array['other', 'coding']::text[], array['recommended', 'tried_tested']::text[], array['Vibe Design: Generer komplekse brugerflader via simple tekstbeskrivelser', 'Code Export: Eksportér direkte til ren HTML, CSS eller Tailwind-kode', 'Figma Integration: Sømløs overførsel af AI-genererede lag til Figma']::text[], 'Gratis (via Google Labs)', 'https://stitch.withgoogle.com/', true, true, 'da', 10),
  ('grok-xai', 'Grok (xAI)', 'Realtids-indsigt med direkte adgang til X-platformen', 'Grok differentierer sig ved at have adgang til realtidsstrømme fra X. For erhvervslivet er det et kraftfuldt værktøj til trend-analyse, brand-monitorering og nyhedsovervågning, før de rammer traditionelle medier.', 'https://abs.twimg.com/favicons/twitter.2.ico', array['text', 'research']::text[], array['tried_tested']::text[], array['Real-time Knowledge: Adgang til live data fra X (tidligere Twitter)', 'Unfiltered Mode: Giver mere direkte og mindre censurerede svar', 'Hurtig responstid og aktuelle begivenheder']::text[], 'Kræver X Premium/Premium+', 'https://x.com/i/grok', false, true, 'da', 11),
  ('heygen', 'HeyGen', 'AI-videoer med realistiske avatarer', 'HeyGen er førende inden for AI-avatarer. Det gør det muligt at producere træningsvideoer og personaliserede salgshilsner i stor skala uden brug af kamera eller skuespillere.', 'https://www.heygen.com/favicon.ico', array['video', 'audio']::text[], array['tried_tested']::text[], array['Video Translation: Oversæt video og synkronisér læber', 'Custom Avatars: Lav en digital kopi af dig selv']::text[], 'Fra $24/md', 'https://www.heygen.com/', false, true, 'da', 12),
  ('ideogram', 'Ideogram', 'Ekspert i præcis tekst i AI-billeder', 'Ideogram løser det klassiske AI-problem med ulæselig tekst i billeder. Perfekt til logo-design, plakater og SoMe-grafik, hvor typografi skal stå knivskarpt.', 'https://ideogram.ai/favicon.ico', array['images']::text[], '{}', array['Typography Engine: Perfekt stavet tekst i billeder', 'Magic Prompt: Hjælper med at udbygge dine korte prompts']::text[], 'Gratis eller $8/md', 'https://ideogram.ai/', false, true, 'da', 13),
  ('lovable', 'Lovable', 'Gør prompts til fuldt funktionelle web-apps', 'Lovable (tidligere GPT Engineer) gør det muligt for ikke-teknikere at bygge komplekse web-apps. Det reducerer udviklingsomkostninger drastisk og forkorter ''time-to-market'' for prototyper.', 'https://lovable.dev/favicon.ico', array['coding', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Full-stack Development: Håndterer både frontend og backend', 'GitHub Integration: Synkroniserer kode direkte til dit repository']::text[], 'Gratis start eller $20/md', 'https://lovable.dev/', true, true, 'da', 14),
  ('microsoft-copilot', 'Microsoft Copilot', 'Din AI-makker til Microsoft 365 og erhvervslivet', 'Copilot transformerer kontorarbejde ved at bygge bro mellem GPT-4 og Microsoft 365. Forretningsværdien ligger i lynhurtig opsummering af Teams-møder, udkast til PowerPoints og dataanalyse i Excel.', 'https://copilot.microsoft.com/favicon.ico', array['text', 'automation']::text[], array['tried_tested']::text[], array['Microsoft 365 Integration: Fungerer inde i Word, Excel og PowerPoint', 'Enterprise Data Protection: Sikrer at virksomhedsdata ikke træner modellen', 'Teams mødeopsummering og handlingspunkter']::text[], 'Gratis (Web) eller licensbaseret (M365)', 'https://copilot.microsoft.com/', false, true, 'da', 15),
  ('midjourney', 'Midjourney', 'Markedets mest kunstneriske AI-billedgenerator', 'Midjourney leverer den højeste æstetiske kvalitet i AI-genererede billeder. For marketingbureauer og designere betyder det adgang til unikke visuelle aktiver uden dyre fotoshoots.', 'https://www.midjourney.com/favicon.ico', array['images', 'video']::text[], array['tried_tested']::text[], array['V6.1 Model: Fotorealistiske og kunstneriske outputs', 'Web Editor: Redigér billeder direkte i browseren']::text[], 'Fra $10/md', 'https://www.midjourney.com/', false, true, 'da', 16),
  ('notebooklm', 'NotebookLM', 'Din personlige AI-forsker baseret på dine data', 'NotebookLM bruger dine egne dokumenter som kildegrundlag. Det er uundværligt til at forstå komplekse projekter og kan endda generere en AI-podcast (Audio Overview) baseret på dine noter.', 'https://www.gstatic.com/notebooklm/favicon.ico', array['text', 'research', 'audio']::text[], array['recommended', 'tried_tested']::text[], array['Source-Grounded: Svarer kun baseret på dine kilder', 'Audio Overview: Transformer noter til en dialog-podcast']::text[], 'Gratis', 'https://notebooklm.google.com/', true, true, 'da', 17),
  ('perplexity-ai', 'Perplexity AI', 'Fremtidens søgemaskine med kildehenvisninger', 'Perplexity sparer virksomheder for timevis af research ved at levere direkte svar med præcise kildehenvisninger. Det sikrer høj troværdighed i beslutningsgrundlag og markedsanalyse.', 'https://www.perplexity.ai/favicon.ico', array['text', 'research']::text[], array['tried_tested']::text[], array['Real-time Search: Gennemsøger internettet for de nyeste data', 'Citations: Direkte links til alle anvendte kilder for faktatjek']::text[], 'Gratis eller $20/md (Pro)', 'https://www.perplexity.ai/', false, true, 'da', 18),
  ('sora-openai', 'Sora (OpenAI)', 'Tekst-til-video der sprænger rammerne', 'Sora er OpenAIs kommende videoværktøj, der kan generere op til 60 sekunders kompleks video. Selvom det stadig er i ''early access'', lover det at revolutionere film- og reklamebranchen.', 'https://openai.com/favicon.ico', array['video']::text[], array['new']::text[], array['High Fidelity: Komplekse scener med præcis fysik', 'Long Duration: Op til 1 minuts video fra én prompt']::text[], 'Endnu ikke offentliggjort', 'https://openai.com/sora/', false, true, 'da', 19),
  ('suno-ai', 'Suno AI', 'Skab komplette sange med vokal på sekunder', 'Suno demokratiserer musikproduktion. For virksomheder er det ideelt til at skabe jingles, baggrundsmusik eller sjove personaliserede sange til interne events uden licensproblemer.', 'https://suno.com/favicon.ico', array['audio']::text[], array['tried_tested']::text[], array['Full Song Generation: Tekst, melodi og vokal i ét', 'Style Prompting: Vælg præcis genre og stemning']::text[], 'Gratis eller $10/md (Pro)', 'https://suno.com/', false, true, 'da', 20),
  ('synthesia', 'Synthesia', 'Nr. 1 platform til Enterprise AI-video', 'Synthesia er guldstandarden for corporate video. Det sparer virksomheder for millioner i videoproduktion ved at lade dem skabe professionelle træningsvideoer blot ved at skrive tekst.', 'https://www.synthesia.io/favicon.ico', array['video', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['140+ Avatarer: Bred diversitet til global brug', 'AI Video Assistant: Skaber scripts og layouts automatisk']::text[], 'Fra $22/md', 'https://www.synthesia.io/', true, true, 'da', 21),
  ('udio', 'Udio', 'Professionel musikkvalitet via AI', 'Udio er kendt for sin ekstremt høje lydkvalitet og musikalske forståelse. Det er værktøjet for dem, der har brug for seriøs komposition og realistisk lydproduktion.', 'https://www.udio.com/favicon.ico', array['audio']::text[], array['recommended', 'tried_tested']::text[], array['High-Fidelity Audio: Studio-kvalitet lyd', 'Extend Tracks: Udbyg dine sange bid for bid']::text[], 'Freemium', 'https://www.udio.com/', false, true, 'da', 22),
  ('adobe-firefly', 'Adobe Firefly', 'Enterprise-safe AI integrated into Creative Cloud', 'Firefly is built for business use with a focus on copyright safety. It''s integrated directly into Photoshop, allowing for lightning-fast image editing via ''Generative Fill''.', 'https://www.adobe.com/favicon.ico', array['images', 'video']::text[], array['tried_tested']::text[], array['Generative Fill: Add or remove objects using text', 'Commercial Safety: Trained on licensed Adobe data']::text[], 'Included in Creative Cloud or Free (limited)', 'https://firefly.adobe.com/', false, true, 'en', 0),
  ('bolt-new', 'Bolt.new', 'Instant web development directly in the browser', 'Bolt.new allows you to build, run, and deploy full web applications directly from your browser via prompts. It eliminates the need for local setup and significantly accelerates the development cycle.', 'https://bolt.new/favicon.ico', array['coding', 'automation']::text[], array['tried_tested']::text[], array['In-browser IDE: Run code without installing anything', 'StackBlitz Integration: Professional development environment']::text[], 'Freemium', 'https://bolt.new/', false, true, 'en', 1),
  ('chatgpt', 'ChatGPT', 'The world''s leading AI assistant for business and productivity.', 'ChatGPT is the gold standard in generative AI, delivering massive ROI by automating knowledge work. It acts as a versatile business partner capable of analyzing complex datasets, generating professional content, and building specialized AI agents (GPTs), saving an average of 40-60 minutes per employee daily.', 'https://upload.wikimedia.org/wikipedia/commons/0/04/ChatGPT_logo.svg', array['text', 'coding', 'images', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Advanced Reasoning: Solves complex logical tasks with GPT-5 technology', 'Custom GPTs: Build your own agents for specific workflows without coding']::text[], 'From $20/mo (Plus) or $25/user (Business)', 'https://chatgpt.com/', true, true, 'en', 2),
  ('claude-anthropic', 'Claude (Anthropic)', 'Advanced AI focused on safety and nuanced reasoning', 'Claude is recognized for its human-like writing style and massive context window. For businesses, it delivers ROI through precise document analysis, coding, and complex problem-solving with lower hallucination rates.', 'https://claude.ai/favicon.ico', array['text', 'coding', 'research']::text[], array['tried_tested']::text[], array['Artifacts: Interactive UI for real-time code and design execution', '200k Context Window: Processing of entire technical manuals or books', 'Superior language nuance and reasoning']::text[], 'Free or $20/mo (Pro)', 'https://claude.ai/', false, true, 'en', 3),
  ('claude-design', 'Claude Design', 'From idea to finished UI design through conversation with Claude', 'Claude Design is Anthropic''s new design tool that lets you generate complete user interfaces, prototypes, and design systems through natural conversation with Claude. Switch between chat and canvas, integrate your own design system, and export to code or Figma. Read our full guide here: /en/articles/claude-design-guide', 'https://claude.ai/favicon.ico', array['other', 'coding']::text[], array['recommended', 'new']::text[], array['Chat and canvas modes for iterative UI design', 'Integration with your own design system and brand tokens', 'Export to code (HTML/CSS/React) or Figma', 'Built into Claude Pro, Max, Team, and Enterprise', 'Multi-screen prototypes and flows in one conversation']::text[], 'Included in Claude Pro (from $20/mo)', 'https://claude.ai/design', false, true, 'en', 4),
  ('elevenlabs', 'ElevenLabs', 'The world''s most realistic AI voices', 'ElevenLabs delivers near-perfect voices for audiobooks, videos, and games. Their voice cloning technology is unrivaled, adding immense value to global content production.', 'https://elevenlabs.io/favicon.ico', array['audio', 'video', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Voice Cloning: Clone your own voice in minutes', 'Speech-to-Speech: Change voice but keep the emotion']::text[], 'Free or $5/mo (Starter)', 'https://elevenlabs.io/', true, true, 'en', 5),
  ('freepik-ai', 'Freepik AI', 'From stock photos to AI-generated graphics', 'Freepik has expanded its massive database with AI tools. This allows marketing teams to generate and customize graphics in one cohesive workflow.', 'https://www.freepik.com/favicon.ico', array['images']::text[], '{}', array['AI Image Generator: Create images directly in the platform', 'Real-time Sketch: Turn simple sketches into finished art']::text[], 'Free or Premium subscription', 'https://www.freepik.com/', false, true, 'en', 6),
  ('gamma', 'Gamma', 'Generate professional presentations in seconds', 'Gamma eliminates the ''blank page'' syndrome by transforming text or prompts into ready-to-use presentations and websites. ROI is found in massive time savings on layout and formatting.', 'https://gamma.app/favicon.ico', array['images', 'text']::text[], '{}', array['One-click Restyling: Change the entire deck''s look instantly', 'AI-Powered Outlines: Generates structure and content automatically']::text[], 'Free (Freemium) or $8/mo', 'https://gamma.app/', false, true, 'en', 7),
  ('google-ai-studio', 'Google AI Studio', 'The developer''s sandbox for Gemini models', 'AI Studio is the ultimate tool for testing and building with Google''s latest models. It provides access to the largest context windows on the market, ideal for analyzing massive datasets.', 'https://aistudio.google.com/favicon.ico', array['coding', 'text', 'automation']::text[], array['tried_tested']::text[], array['2M Context Window: Analyze giant datasets or hours of video', 'API Key Management: Easy transition from prototype to production']::text[], 'Free (within quotas)', 'https://aistudio.google.com/', false, true, 'en', 8),
  ('google-gemini', 'Google Gemini', 'Multimodal intelligence integrated with Google Workspace', 'Gemini is Google''s most capable AI, excelling in multimodality. It drives business value by connecting directly to Google Workspace, automating workflows across Docs, Gmail, and Drive.', 'https://www.gstatic.com/lamda/images/favicon_v1_150160d13988652c776.png', array['text', 'automation', 'images']::text[], array['recommended', 'tried_tested']::text[], array['Native Multimodality: Understands text, images, video, and audio in one prompt', 'Google Workspace Integration: Pull data directly from Gmail and Drive', 'Extremely fast response times']::text[], 'Free or $20/mo (Advanced)', 'https://gemini.google.com/app', true, true, 'en', 9),
  ('google-stitch', 'Google Stitch', 'From vision to production-ready UI in seconds', 'Google Stitch is a cutting-edge AI design tool that transforms natural language prompts or sketches into high-fidelity UI designs and production-ready frontend code. For businesses, this means a significant reduction in time-to-market for MVPs and digital products, as the bridge between idea, design, and code is automated via Google''s Gemini models.', 'https://stitch.withgoogle.com/static/favicon.png', array['other', 'coding']::text[], array['recommended', 'tried_tested']::text[], array['Vibe Design: Generate complex user interfaces via simple text prompts', 'Code Export: Export directly to clean HTML, CSS, or Tailwind code', 'Figma Integration: Seamless transfer of AI-generated layers to Figma']::text[], 'Free (via Google Labs)', 'https://stitch.withgoogle.com/', true, true, 'en', 10),
  ('grok-xai', 'Grok (xAI)', 'Real-time insights with direct access to the X platform', 'Grok differentiates itself through access to the real-time stream of X. For business, it''s a powerful tool for trend analysis, brand monitoring, and tracking news before they hit traditional media.', 'https://abs.twimg.com/favicons/twitter.2.ico', array['text', 'research']::text[], array['tried_tested']::text[], array['Real-time Knowledge: Access to live data from X (formerly Twitter)', 'Unfiltered Mode: Provides more direct and less censored answers', 'Fast response times and current events']::text[], 'Requires X Premium/Premium+', 'https://x.com/i/grok', false, true, 'en', 11),
  ('heygen', 'HeyGen', 'AI videos with realistic avatars', 'HeyGen is a leader in AI avatars. It enables the production of training videos and personalized sales messages at scale without cameras or actors.', 'https://www.heygen.com/favicon.ico', array['video', 'audio']::text[], array['tried_tested']::text[], array['Video Translation: Translate video and sync lip movements', 'Custom Avatars: Create a digital twin of yourself']::text[], 'From $24/mo', 'https://www.heygen.com/', false, true, 'en', 12),
  ('ideogram', 'Ideogram', 'Expert in precise text within AI images', 'Ideogram solves the classic AI problem of unreadable text in images. Perfect for logo design, posters, and social media graphics where typography must be crisp.', 'https://ideogram.ai/favicon.ico', array['images']::text[], '{}', array['Typography Engine: Perfectly spelled text in images', 'Magic Prompt: Helps expand your short prompts']::text[], 'Free or $8/mo', 'https://ideogram.ai/', false, true, 'en', 13),
  ('lovable', 'Lovable', 'Turn prompts into fully functional web apps', 'Lovable enables non-technical users to build complex web apps. It drastically reduces development costs and shortens time-to-market for prototypes.', 'https://lovable.dev/favicon.ico', array['coding', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['Full-stack Development: Handles both frontend and backend', 'GitHub Integration: Syncs code directly to your repository']::text[], 'Free start or $20/mo', 'https://lovable.dev/', true, true, 'en', 14),
  ('microsoft-copilot', 'Microsoft Copilot', 'Your AI companion for Microsoft 365 and business', 'Copilot transforms office work by bridging GPT-4 with Microsoft 365. Business value is delivered through instant Teams meeting summaries, PowerPoint drafts, and Excel data analysis.', 'https://copilot.microsoft.com/favicon.ico', array['text', 'automation']::text[], array['tried_tested']::text[], array['Microsoft 365 Integration: Works inside Word, Excel, and PowerPoint', 'Enterprise Data Protection: Ensures corporate data is not used for training', 'Teams meeting summaries and action items']::text[], 'Free (Web) or License-based (M365)', 'https://copilot.microsoft.com/', false, true, 'en', 15),
  ('midjourney', 'Midjourney', 'The market''s most artistic AI image generator', 'Midjourney delivers the highest aesthetic quality in AI-generated images. For marketing agencies and designers, this means access to unique visual assets without expensive photoshoots.', 'https://www.midjourney.com/favicon.ico', array['images', 'video']::text[], array['tried_tested']::text[], array['V6.1 Model: Photorealistic and artistic outputs', 'Web Editor: Edit images directly in the browser']::text[], 'From $10/mo', 'https://www.midjourney.com/', false, true, 'en', 16),
  ('notebooklm', 'NotebookLM', 'Your personal AI researcher based on your data', 'NotebookLM uses your own documents as its knowledge base. It''s essential for understanding complex projects and can even generate an AI podcast (Audio Overview) based on your notes.', 'https://www.gstatic.com/notebooklm/favicon.ico', array['text', 'research', 'audio']::text[], array['recommended', 'tried_tested']::text[], array['Source-Grounded: Only answers based on your sources', 'Audio Overview: Transforms notes into a dialogue-style podcast']::text[], 'Free', 'https://notebooklm.google.com/', true, true, 'en', 17),
  ('perplexity-ai', 'Perplexity AI', 'The future of search with source citations', 'Perplexity saves businesses hours of research by providing direct answers with precise citations. It ensures high credibility in decision-making and market analysis.', 'https://www.perplexity.ai/favicon.ico', array['text', 'research']::text[], array['tried_tested']::text[], array['Real-time Search: Scours the web for the latest data', 'Citations: Direct links to all sources used for fact-checking']::text[], 'Free or $20/mo (Pro)', 'https://www.perplexity.ai/', false, true, 'en', 18),
  ('sora-openai', 'Sora (OpenAI)', 'Text-to-video that breaks boundaries', 'Sora is OpenAI''s upcoming video tool, capable of generating up to 60 seconds of complex video. While still in early access, it promises to revolutionize film and advertising.', 'https://openai.com/favicon.ico', array['video']::text[], array['new']::text[], array['High Fidelity: Complex scenes with accurate physics', 'Long Duration: Up to 1 minute of video from a single prompt']::text[], 'Not yet released', 'https://openai.com/sora/', false, true, 'en', 19),
  ('suno-ai', 'Suno AI', 'Create full songs with vocals in seconds', 'Suno democratizes music production. For businesses, it''s ideal for creating jingles, background music, or fun personalized songs for internal events without licensing issues.', 'https://suno.com/favicon.ico', array['audio']::text[], array['tried_tested']::text[], array['Full Song Generation: Lyrics, melody, and vocals in one', 'Style Prompting: Choose exact genre and mood']::text[], 'Free or $10/mo (Pro)', 'https://suno.com/', false, true, 'en', 20),
  ('synthesia', 'Synthesia', '#1 platform for Enterprise AI video', 'Synthesia is the gold standard for corporate video. It saves companies millions in production costs by enabling them to create professional training videos just by typing text.', 'https://www.synthesia.io/favicon.ico', array['video', 'automation']::text[], array['recommended', 'tried_tested']::text[], array['140+ Avatars: High diversity for global reach', 'AI Video Assistant: Creates scripts and layouts automatically']::text[], 'From $22/mo', 'https://www.synthesia.io/', true, true, 'en', 21),
  ('udio', 'Udio', 'Professional music quality through AI', 'Udio is known for its extremely high audio quality and musical understanding. It''s the tool for those needing serious composition and realistic sound production.', 'https://www.udio.com/favicon.ico', array['audio']::text[], array['recommended', 'tried_tested']::text[], array['High-Fidelity Audio: Studio-quality sound', 'Extend Tracks: Build out your songs bit by bit']::text[], 'Freemium', 'https://www.udio.com/', false, true, 'en', 22)
on conflict (slug, locale) do nothing;

insert into public.use_cases (slug, title, reference, department, complexity, strategic_value, problem_statement, solution, business_benefits, recommended_tools, featured, published, locale, sort_order) values
  ('ai-mus-samtaler', 'AI-assisteret MUS-samtale og opfølgning', 'UC-101', 'hr', 'low', 'quality', 'Ledere bruger ofte MUS-samtaler på at tage noter i stedet for at lytte aktivt. Referater bliver uensartede, og opfølgning på udviklingsmål falder mellem to stole.', 'Brug AI til at transskribere samtalen i realtid via Microsoft Teams, og lad derefter en AI-assistent strukturere referatet efter faste fokusområder. Efter alle samtaler kan AI identificere fælles temaer på tværs af teamet og generere en samlet opfølgningskalender.', array['Mere nærvær og aktiv lytning i samtalen', 'Ensartede og strukturerede referater på 5 minutter', 'Tværgående analyse af udviklingsmål og temaer', 'Automatisk opfølgningskalender med deadlines', 'Bedre medarbejderoplevelse og højere trivsel']::text[], array['Microsoft Teams', 'ChatGPT', 'Claude', 'Copilot']::text[], true, true, 'da', 0),
  ('accelereret-softwareudvikling', 'Accelereret softwareudvikling og kodegenerering', '#5', 'it', 'high', 'efficiency', 'Udviklingsteams er ofte flaskehalse pga. manuelle, repetitive kodeopgaver og mangel på ressourcer.', 'Gen AI assisterer professionelle udviklere med at skrive, optimere og teste kode lynhurtigt, hvilket reducerer udviklingstiden for nye features dramatisk.', array['Markant kortere ''Time-to-Market'' for nye softwareprodukter.', 'Frigørelse af seniorudviklere til arkitektur og komplekse problemer.', 'Reduktion af manuelle fejl i rutinepræget kodning.']::text[], array['GitHub Copilot', 'Cursor', 'ChatGPT (GPT-4o)']::text[], false, true, 'da', 1),
  ('ai-empatisk-stoette-trivsel', 'AI som empatisk støtte: Fremtidens trivsel og mental sundhed', '#1', 'hr', 'low', 'quality', 'Mange medarbejdere oplever ensomhed, mental træthed eller mangel på en fortrolig samtalepartner i en travl hverdag, hvilket kan føre til nedsat trivsel og højere sygefravær.', 'Generativ AI fungerer som en virtuel ledsager, der tilbyder emotionel støtte, lytter uden fordomme og genererer empatiske svar for at hjælpe medarbejdere med at håndtere hverdagens udfordringer og mentale barrierer.', array['Reducerer barrieren for mental støtte ved at tilbyde en anonym og altid tilgængelig samtalepartner.', 'Forbedrer medarbejdertrivsel gennem daglig refleksion, humør-analyse og støtte til personlige gennembrud.', 'Frigør menneskelige ressourcer ved at lade AI håndtere lavpraktisk emotionel støtte og daglig strukturering af mentale opgaver.']::text[], array['ChatGPT', 'Pi (Inflection AI)', 'Woebot']::text[], false, true, 'da', 2),
  ('ai-katalysator-kreativitet', 'AI som katalysator for grænsebrydende kreativitet', '#9', 'marketing', 'medium', 'growth', 'Virksomheder begrænses ofte af traditionelle produktionsmetoder og budgetter til visuelt indhold.', 'Ved at bruge generative modeller til billeder, video og lyd kan virksomheder producere ''high-end'' kreativt indhold, der før var umuligt at skabe in-house.', array['Skalering af indholdsproduktion uden massive produktionsomkostninger.', 'Unik visuel differentiering i et mættet marked.', 'Mulighed for lynhurtigt at teste mange forskellige visuelle udtryk.']::text[], array['Midjourney', 'Adobe Firefly', 'Runway']::text[], false, true, 'da', 3),
  ('ai-sundhedsraadgivning-symptomcheck', 'AI Sundhedsrådgivning & Symptomcheck', '#26', 'hr', 'high', 'efficiency', 'Mange medarbejdere bruger tid i arbejdstiden på sundhedsspørgsmål, der kunne afklares hurtigt med korrekt information.', 'Avanceret AI analyserer symptomer og medicinske data for at give præcis, personlig vejledning og triagering.', array['Hurtigere afklaring af sundhedsspørgsmål, hvilket minimerer unødigt fravær.', 'Forbedret sundhedsprofil for medarbejdere gennem forebyggende råd.', 'Optimeret brug af virksomhedens sundhedsforsikring gennem korrekt triagering.']::text[], array['Ada Health', 'Babylon AI', 'Glass Health']::text[], false, true, 'da', 4),
  ('ai-assisteret-rapportskrivning-uddannelse', 'AI-assisteret Rapportskrivning og Uddannelse', '#23', 'hr', 'low', 'quality', 'Udarbejdelse af træningsmateriale og faglige rapporter er tidskrævende og resulterer ofte i tørt, uoverskueligt indhold.', 'Gen AI assisterer med at strukturere komplekse emner, lave outlines og udkast til velresearchede rapporter og kursusmateriale.', array['Hurtigere produktion af interne rapporter og uddannelsesdokumentation.', 'Forbedret kvalitet og struktur i skriftlig formidling på tværs af organisationen.', 'Effektiv hjælp til medarbejdere under efteruddannelse.']::text[], array['ChatGPT', 'Claude', 'Jasper']::text[], false, true, 'da', 5),
  ('ai-assisteret-troubleshooting', 'AI-assisteret Troubleshooting', '#16', 'it', 'medium', 'efficiency', 'Nedetid på maskiner eller systemer koster dyrt, og teknikerbesøg er langsomme og bekostelige.', 'AI analyserer fejlkoder, billeder af defekt hardware og historiske data for at give øjeblikkelige reparationsvejledninger.', array['Markant reduktion i Mean Time to Repair (MTTR).', 'Besparelser på eksterne konsulenter og mekanikere ved gør-det-selv løsninger.', 'Demokratisering af teknisk viden – alle kan udføre basal fejlfinding.']::text[], array['ChatGPT Vision', 'Claude 3.5 Sonnet', 'Fixit AI']::text[], false, true, 'da', 6),
  ('ai-baseret-mental-support-trivsel', 'AI-baseret Mental Support og Trivsel', '#25', 'hr', 'medium', 'quality', 'Medarbejdernes mentale sundhed er under pres, og adgang til øjeblikkelig sparring eller støtte er ofte begrænset.', 'AI-modeller fungerer som empatiske lyttepartnere eller virtuelle coaches, der tilbyder vejledning og mestringsstrategier i realtid.', array['Øget medarbejdertrivsel gennem let tilgængelig lavtærskel-støtte.', 'Reduktion i sygefravær relateret til stress gennem tidlig indsats.', 'Skaber et trygt rum for medarbejdere til at lufte tanker anonymt.']::text[], array['Woebot', 'Wysa', 'ChatGPT']::text[], false, true, 'da', 7),
  ('ai-drevet-interviewforberedelse', 'AI-drevet Interviewforberedelse', '#11', 'hr', 'low', 'quality', 'Kandidater og medarbejdere føler sig ofte uforberedte og stressede før vigtige samtaler, hvilket fører til underpræstation.', 'Gen AI simulerer realistiske interview-scenarier og giver øjeblikkelig feedback på svar, kropssprog og toneleje.', array['Øget selvtillid hos medarbejdere før interne og eksterne præsentationer.', 'Højere kvalitet i kandidat-screening gennem bedre forberedte interviewere.', 'Reduktion af stressrelaterede fejl under vigtige forretningskald.']::text[], array['ChatGPT Voice Mode', 'Claude', 'Interviewer.ai']::text[], false, true, 'da', 8),
  ('ai-drevet-projektplanlaegning', 'AI-drevet Projektplanlægning', '#20', 'operations', 'low', 'efficiency', 'Projekter fejler ofte på grund af urealistiske tidsplaner og manglende overblik over delopgaver.', 'Gen AI opstiller strukturerede planer, milepæle og opgavelister baseret på overordnede mål.', array['Hurtigere overgang fra idé til eksekverbar plan.', 'Bedre identifikation af potentielle flaskehalse i projektforløbet.', 'Øget gennemsigtighed og struktur i team-samarbejde.']::text[], array['Asana Intelligence', 'ChatGPT', 'Monday.com AI']::text[], false, true, 'da', 9),
  ('ai-genereret-underholdning-aktiviteter', 'AI-genereret Underholdning og Aktiviteter', '#21', 'marketing', 'low', 'quality', 'Virksomheder kæmper med at skabe engagerende og unikt indhold til familie-events eller kundesegmenter med børn.', 'Gen AI skaber personlige historier, interaktive spil og kreative opgaver, der er skræddersyet til specifikke aldersgrupper og temaer.', array['Øget kundeloyalitet gennem unikke, personaliserede oplevelser for børnefamilier.', 'Markant tidsbesparelse i planlægning af firma-events og workshops.', 'Mulighed for lynhurtigt at skalere kreative koncepter til forskellige platforme.']::text[], array['ChatGPT', 'Midjourney', 'StoryBird AI']::text[], false, true, 'da', 10),
  ('ai-understoettet-trivsel', 'AI-understøttet trivsel og sundhedsfremme', '#10', 'hr', 'low', 'quality', 'Medarbejdernes sundhed og trivsel er afgørende for produktiviteten, men personlig rådgivning er dyrt og svært at skalere.', 'Gen AI tilbyder personaliserede sundhedsplaner, kostvejledning og wellness-tips baseret på den enkelte medarbejders livsstil og mål.', array['Reduceret sygefravær gennem fokus på forebyggende sundhed.', 'Øget medarbejderenergi og fokus i løbet af arbejdsdagen.', 'En stærk værditilføjelse til virksomhedens personalegoder (Employer Branding).']::text[], array['MyFitnessPal (AI)', 'ChatGPT', 'Oura (AI insights)']::text[], false, true, 'da', 11),
  ('automatiseret-generering-juridiske-dokumenter', 'Automatiseret Generering af Juridiske Dokumenter', '#28', 'operations', 'high', 'efficiency', 'Udarbejdelse af standardkontrakter og juridiske dokumenter tager lang tid og er dyrt i advokatomkostninger.', 'Gen AI genererer skræddersyede juridiske udkast baseret på specifikke input, hvilket sikrer konsistens og korrekt formatering.', array['Markant besparelse på juridiske omkostninger ved standardiserede opgaver.', 'Hurtigere ekspeditionstid for kontrakter og aftaler.', 'Reduktion i menneskelige fejl gennem brug af præcise skabeloner.']::text[], array['Harvey AI', 'Ironclad', 'Spellbook']::text[], false, true, 'da', 12),
  ('automatiseret-generering-billeder', 'Automatiseret Generering af Relevante Billeder', '#12', 'marketing', 'medium', 'efficiency', 'Virksomheder bruger for mange ressourcer på stock-billeder eller dyre grafiske processer til blogs og sociale medier.', 'Gen AI skaber unikke, brand-specifikke billeder lynhurtigt baseret på tekstbeskrivelser.', array['Drastisk reduktion i omkostninger til stock-fotos og eksterne grafikere.', 'Hurtigere time-to-market for visuelt indhold til kampagner.', 'Unik visuel identitet uden risiko for at bruge de samme billeder som konkurrenter.']::text[], array['Midjourney', 'DALL-E 3', 'Canva Magic Design']::text[], false, true, 'da', 13),
  ('boost-selvtillid-beslutningskraft', 'Boost Selvtillid og Beslutningskraft', '#18', 'operations', 'low', 'quality', 'Usikkerhed hos medarbejdere fører til tøven og manglende initiativ i vigtige projekter.', 'AI fungerer som en sparringspartner, der bekræfter beslutninger, giver positiv feedback og perspektiverer udfordringer.', array['Hurtigere beslutningsprocesser ved at have en AI backup.', 'Større risikovillighed og innovation hos medarbejdere.', 'Forbedret psykologisk tryghed gennem objektiv feedback og støtte.']::text[], array['ChatGPT', 'Pi', 'Claude']::text[], false, true, 'da', 14),
  ('corporate-llm-intern-copilot', 'Corporate LLM & Intern Copilot', '#22', 'it', 'high', 'efficiency', 'Medarbejdere drukner i interne data og bruger for meget tid på at søge efter svar i ustrukturerede dokumenter.', 'Implementering af en lukket virksomheds-LLM, der fungerer som en intelligent assistent på tværs af dokumenter, support og dataanalyse.', array['Radikal forbedring af medarbejdernes produktivitet ved hurtig adgang til intern viden.', 'Sikker håndtering af følsomme data inden for virksomhedens eget setup.', 'Automatisering af rutineprægede supportopgaver og dokumentgenerering.']::text[], array['Azure OpenAI', 'Microsoft Copilot', 'Custom LLM stack']::text[], false, true, 'da', 15),
  ('eksponentiel-idegenerering', 'Eksponentiel idégenerering og konceptualisering', '#6', 'marketing', 'low', 'growth', 'Kreativ stilstand i marketing og produktudvikling hæmmer innovation og konkurrenceevne.', 'Gen AI fungerer som en uendelig kilde til kreative idéer, der kan kombinere datamønstre og trends til nye koncepter på sekunder.', array['10x flere idéer på kortere tid i brainstorming-sessioner.', 'Hurtigere identifikation af vindende kampagnekoncepter.', 'Billig eksperimentering med ''wildcard'' idéer uden risiko.']::text[], array['Claude.ai', 'Miro Assist', 'Midjourney']::text[], false, true, 'da', 16),
  ('engagement-kreativt-indhold', 'Engagement gennem kreativt og underholdende indhold', '#7', 'marketing', 'low', 'quality', 'Statisk og kedeligt indhold overses af kunderne, hvilket fører til lav brand-bevidsthed og engagement.', 'Gen AI bruges til at skabe sjovt, humoristisk og viralt potentiale gennem memes, skæve scenarier og kreativ leg med brandet.', array['Højere engagement på sociale medier gennem relevant humor.', 'Humanisering af brandet ved at vise personlighed og kreativitet.', 'Lavere omkostninger til produktion af ''lightweight'' underholdningsindhold.']::text[], array['Midjourney', 'Suno', 'ChatGPT']::text[], false, true, 'da', 17),
  ('formaalsdrevet-karriereudvikling', 'Formålsdrevet karriereudvikling og selvrefleksion', '#3', 'hr', 'medium', 'quality', 'Manglende retning og formål i arbejdet er en af de største årsager til medarbejderflugt og lavt engagement.', 'Ved hjælp af Gen AI kan medarbejdere gennemgå guidede refleksionsforløb, der matcher deres personlige værdier med virksomhedens mission og karrieremuligheder.', array['Højere medarbejderfastholdelse gennem øget arbejdsglæde og mening.', 'Bedre udnyttelse af medarbejdernes skjulte talenter og passioner.', 'Styrket virksomhedskultur baseret på fælles værdier.']::text[], array['Claude.ai', 'ChatGPT', 'Mindgrasp']::text[], false, true, 'da', 18),
  ('hyper-personaliseret-laering', 'Hyper-personaliseret læring og kompetenceløft', '#4', 'hr', 'low', 'quality', 'Standardiserede kurser rammer ofte ved siden af medarbejderens reelle behov, hvilket spilder tid og ressourcer.', 'Gen AI skaber interaktivt læringsindhold, der tilpasser sig den enkeltes stil, tempo og eksisterende viden, hvilket gør træningen langt mere effektiv.', array['Markant hurtigere opkvalificering af medarbejdere (upskilling).', 'Reduceret tidsforbrug på irrelevant træningsmateriale.', 'Instant feedback-loop, der sikrer korrekt indlæring fra start.']::text[], array['Learnai.nu Custom Tutor', 'Kajabi', 'ChatGPT Team']::text[], false, true, 'da', 19),
  ('hyper-specifik-vidensoegning', 'Hyper-specifik Vidensøgning', '#13', 'operations', 'low', 'efficiency', 'Medarbejdere spilder tid på at lede efter specifik information i massive datasæt eller gennem upræcise Google-søgninger.', 'AI-modeller syntetiserer information fra flere kilder og leverer direkte svar på komplekse, tekniske spørgsmål.', array['Markant tidsbesparelse ved research af tekniske komponenter eller regulativer.', 'Evnen til at identificere objekter eller dele via billedgenkendelse i felten.', 'Hurtigere beslutningstagning baseret på præcis informationssyntese.']::text[], array['Perplexity AI', 'ChatGPT Search', 'Glean']::text[], false, true, 'da', 20),
  ('intelligent-beskyttelse-mod-trolling', 'Intelligent Beskyttelse mod Trolling', '#30', 'marketing', 'medium', 'quality', 'Online communities og sociale medier kan hurtigt blive oversvømmet af negativitet og trolling, hvilket skader brandet.', 'AI detekterer skadelige kommentarer i realtid og foreslår moderationsstrategier eller konstruktive modsvar.', array['Beskyttelse af brandets omdømme gennem sundere online miljøer.', 'Besparelser på manuel moderation og community management.', 'Bedre kundeoplevelse i virksomhedens digitale kanaler.']::text[], array['OpenAI Moderation API', 'CleanSpeak', 'Perspective API']::text[], false, true, 'da', 21),
  ('intelligent-rejseplanlaegning-erhverv', 'Intelligent Rejseplanlægning for Erhverv', '#24', 'operations', 'low', 'efficiency', 'Planlægning af komplekse forretningsrejser med flere stop, møder og logistik er en administrativ byrde.', 'AI optimerer rejseplaner baseret på præferencer, tidsskemaer og budget, og leverer en fuldstændig optimeret ruteplan.', array['Drastisk reduktion i tidsforbrug på rejseadministration.', 'Bedre optimering af tid mellem møder, hvilket øger effektiviteten på farten.', 'Reducerede rejseomkostninger gennem AI-identificerede prisoptimeringer.']::text[], array['ChatGPT with Travel Plugins', 'Roam Around', 'Tripnotes']::text[], false, true, 'da', 22),
  ('intelligent-strukturering-arbejdsdag', 'Intelligent strukturering af arbejdsdag og prioriteter', '#2', 'operations', 'low', 'efficiency', 'Mange medarbejdere lider under ''information overload'' og har svært ved at prioritere opgaver, hvilket fører til stress og nedsat produktivitet.', 'Gen AI fungerer som en personlig driftsassistent, der analyserer opgavelister, deadlines og mål for at skabe en optimeret tidsplan og strukturere det fysiske og digitale arbejdsmiljø.', array['Øget output gennem bedre tidsstyring og eliminering af tidsrøvere.', 'Reduceret stressniveau hos medarbejdere grundet klarere overblik.', 'Bedre alignment mellem daglige opgaver og overordnede strategiske mål.']::text[], array['ChatGPT', 'Notion AI', 'Reclaim.ai']::text[], false, true, 'da', 23),
  ('konfliktloesning-maegling-ai', 'Konfliktløsning og Mægling med AI', '#27', 'hr', 'medium', 'quality', 'Personlige konflikter på arbejdspladsen kan eskalere og skade arbejdsmiljøet, hvis de ikke håndteres objektivt.', 'AI analyserer kommunikationsmønstre og tilbyder neutrale perspektiver samt mæglingsteknikker til at løse uoverensstemmelser.', array['Hurtigere løsning af interne tvister før de bliver til alvorlige HR-sager.', 'Fremmer en sundere feedback-kultur gennem objektive analyser.', 'Reduktion i stress og frustration hos de involverede parter.']::text[], array['ChatGPT', 'Claude', 'Cresta']::text[], false, true, 'da', 24),
  ('optimering-kodebase-refactoring', 'Optimering af eksisterende kodebase (Refactoring)', '#8', 'it', 'high', 'quality', 'Gammel kode (legacy code) og teknisk gæld gør systemer langsomme, usikre og svære at vedligeholde.', 'Gen AI analyserer eksisterende kode for at finde fejl, optimere ydeevnen og foreslå moderne alternativer, hvilket forbedrer systemstabiliteten.', array['Reduktion af teknisk gæld og vedligeholdelsesomkostninger.', 'Højere systemsikkerhed gennem automatisk fejlfinding.', 'Forbedret performance og hastighed i kritiske forretningssystemer.']::text[], array['GitHub Copilot', 'Cursor', 'SonarQube (AI features)']::text[], false, true, 'da', 25),
  ('personlig-laering-coaching', 'Personlig Læring og Coaching', '#17', 'hr', 'medium', 'quality', 'Traditionel efteruddannelse er ofte one-size-fits-all og ineffektiv til at lukke specifikke kompetencegab.', 'AI fungerer som en personlig tutor, der tilpasser undervisningsmateriale og sværhedsgrad til den enkelte medarbejder.', array['Hurtigere kompetenceudvikling gennem adaptiv læring.', '24/7 adgang til en tålmodig tutor, der aldrig mister overblikket.', 'Øget fastholdelse af viden gennem interaktive quizzer og feedback.']::text[], array['Khanmigo', 'ChatGPT Personal Tutor', 'Coursera Coach']::text[], false, true, 'da', 26),
  ('ressourceoptimering-kokkerer-med-hvad-du-har', 'Ressourceoptimering: Kokkerér med hvad du har', '#15', 'operations', 'low', 'efficiency', 'Spild af eksisterende ressourcer eller lagerbeholdning på grund af manglende overblik over anvendelsesmuligheder.', 'AI foreslår kreative løsninger eller opskrifter baseret udelukkende på de tilgængelige input og ingredienser.', array['Reduktion af madspild i kantiner og restaurationsbranchen.', 'Optimeret brug af eksisterende lagerbeholdning før nyindkøb.', 'Kreativ problemløsning i logistik ved at maksimere brug af tilgængelige midler.']::text[], array['ChatGPT Vision', 'Chef GPT', 'Custom GPTs']::text[], false, true, 'da', 27),
  ('simple-forklaringer-kompleks-dokumentation', 'Simple Forklaringer af Kompleks Dokumentation', '#14', 'operations', 'medium', 'quality', 'Tekniske manualer og API-dokumentation er ofte uforståelige for ikke-eksperter, hvilket skaber flaskehalse.', 'Gen AI nedbryder kompleks viden til letfordøjelige forklaringer (ELI5) skræddersyet til modtagerens niveau.', array['Frigør tid for specialister ved at lade AI besvare basale tekniske spørgsmål.', 'Forbedret kundeservice gennem hurtigere forståelse af komplekse sager.', 'Hurtigere onboarding af nye medarbejdere i komplekse systemer.']::text[], array['ChatPDF', 'NotebookLM', 'ChatGPT']::text[], false, true, 'da', 28),
  ('strategisk-sparring-dybe-dialoger', 'Strategisk Sparring og Dybe Dialoger', '#29', 'hr', 'medium', 'quality', 'Ledere og specialister mangler ofte en fortrolig partner til at udforske komplekse tanker og strategiske dilemmaer.', 'AI faciliterer reflekterende dialoger ved at stille udfordrende spørgsmål og give nye indsigter i en tryg ramme.', array['Styrket lederskab gennem dybere refleksion og selverkendelse.', 'Innovative løsninger på komplekse forretningsmæssige udfordringer.', 'Øget mental klarhed for nøglemedarbejdere.']::text[], array['Pi', 'ChatGPT Plus', 'Claude']::text[], false, true, 'da', 29),
  ('strategisk-tone-of-voice-justering', 'Strategisk Tone-of-Voice Justering', '#19', 'marketing', 'low', 'quality', 'E-mails og kommunikation kan ofte misforstås som konfrontatoriske eller uklare, hvilket skader relationer.', 'AI analyserer og omskriver tekster for at ramme den præcise ønskede tone (professionel, venlig, empatisk).', array['Færre konflikter i intern og ekstern korrespondance.', 'Sikrer at virksomhedens brand voice overholdes af alle.', 'Mere effektiv kommunikation til kulturelt forskelligartede modtagere.']::text[], array['Grammarly Business', 'Jasper', 'ChatGPT']::text[], false, true, 'da', 30),
  ('ai-performance-reviews', 'AI-Assisted Performance Reviews and Follow-up', 'UC-101', 'hr', 'low', 'quality', 'Managers often spend performance reviews taking notes instead of actively listening. Summaries become inconsistent, and follow-up on development goals falls through the cracks.', 'Use AI to transcribe the conversation in real-time via Microsoft Teams, then let an AI assistant structure the summary according to fixed focus areas. After all reviews, AI can identify common themes across the team and generate a consolidated follow-up calendar.', array['More presence and active listening in conversations', 'Consistent structured summaries in 5 minutes', 'Cross-team analysis of development goals and themes', 'Automatic follow-up calendar with deadlines', 'Better employee experience and higher well-being']::text[], array['Microsoft Teams', 'ChatGPT', 'Claude', 'Copilot']::text[], true, true, 'en', 0),
  ('accelerated-software-development', 'Accelerated Software Development and Code Generation', '#5', 'it', 'high', 'efficiency', 'Development teams are often bottlenecks due to manual, repetitive coding tasks and resource shortages.', 'Gen AI assists professional developers in writing, optimizing, and testing code rapidly, dramatically reducing the development time for new features.', array['Significantly shorter Time-to-Market for new software products.', 'Freeing up senior developers for architecture and complex problems.', 'Reduction of manual errors in routine coding.']::text[], array['GitHub Copilot', 'Cursor', 'ChatGPT (GPT-4o)']::text[], false, true, 'en', 1),
  ('ai-catalyst-creativity', 'AI as a Catalyst for Boundary-Breaking Creativity', '#9', 'marketing', 'medium', 'growth', 'Companies are often limited by traditional production methods and budgets for visual content.', 'By using generative models for images, video, and audio, companies can produce high-end creative content that was previously impossible to create in-house.', array['Scaling content production without massive production costs.', 'Unique visual differentiation in a saturated market.', 'Ability to rapidly test many different visual styles.']::text[], array['Midjourney', 'Adobe Firefly', 'Runway']::text[], false, true, 'en', 2),
  ('ai-empathetic-support-wellbeing', 'AI as Empathetic Support: The Future of Wellbeing', '#1', 'hr', 'low', 'quality', 'Many employees experience loneliness, mental fatigue, or the lack of a confidential sparring partner in a busy workday, leading to decreased wellbeing and potential burnout.', 'Generative AI acts as a virtual companion, offering emotional support, providing a listening ear, and generating empathetic responses to support individuals in their personal and professional healing journey.', array['Lowers the barrier to mental health support by providing an anonymous, 24/7 accessible conversational partner.', 'Enhances employee wellbeing through daily reflection, mood analysis, and support for personal breakthroughs.', 'Frees up human resources by allowing AI to handle low-barrier emotional support and daily mental structuring.']::text[], array['ChatGPT', 'Pi (Inflection AI)', 'Woebot']::text[], false, true, 'en', 3),
  ('ai-conflict-resolution-mediation', 'AI Conflict Resolution and Mediation', '#27', 'hr', 'medium', 'quality', 'Personal workplace disputes can escalate and damage the environment if not handled objectively.', 'AI analyzes communication patterns and offers neutral perspectives and mediation techniques to resolve disputes.', array['Faster resolution of internal disputes before they become serious HR issues.', 'Promotes a healthier feedback culture through objective analysis.', 'Reduction in stress and frustration for the involved parties.']::text[], array['ChatGPT', 'Claude', 'Cresta']::text[], false, true, 'en', 4),
  ('ai-medical-advice-symptom-checking', 'AI Medical Advice & Symptom Checking', '#26', 'hr', 'high', 'efficiency', 'Many employees spend work time on health questions that could be resolved quickly with accurate information.', 'Advanced AI analyzes symptoms and medical data to provide precise, personalized guidance and triaging.', array['Faster clarification of health issues, minimizing unnecessary absenteeism.', 'Improved employee health profile through preventive advice.', 'Optimized use of company health insurance through correct triaging.']::text[], array['Ada Health', 'Babylon AI', 'Glass Health']::text[], false, true, 'en', 5),
  ('ai-assisted-report-writing-education', 'AI-Assisted Report Writing and Education', '#23', 'hr', 'low', 'quality', 'Creating training materials and professional reports is time-consuming and often results in dry, overwhelming content.', 'Gen AI assists in structuring complex topics, creating outlines, and drafting well-researched reports and course materials.', array['Faster production of internal reports and educational documentation.', 'Improved quality and structure in written communication across the organization.', 'Effective support for employees undergoing professional development.']::text[], array['ChatGPT', 'Claude', 'Jasper']::text[], false, true, 'en', 6),
  ('ai-assisted-troubleshooting', 'AI-Assisted Troubleshooting', '#16', 'it', 'medium', 'efficiency', 'Downtime on machinery or systems is costly, and technician visits are slow and expensive.', 'AI analyzes error codes, images of faulty hardware, and historical data to provide instant repair guides.', array['Significant reduction in Mean Time to Repair (MTTR).', 'Savings on external consultants and mechanics through DIY solutions.', 'Democratization of technical knowledge – anyone can perform basic troubleshooting.']::text[], array['ChatGPT Vision', 'Claude 3.5 Sonnet', 'Fixit AI']::text[], false, true, 'en', 7),
  ('ai-based-mental-support-wellbeing', 'AI-Based Mental Support and Well-being', '#25', 'hr', 'medium', 'quality', 'Employee mental health is under pressure, and access to immediate sparring or support is often limited.', 'AI models act as empathetic listening partners or virtual coaches, offering guidance and coping strategies in real-time.', array['Increased employee well-being through easily accessible low-barrier support.', 'Reduction in stress-related absenteeism through early intervention.', 'Creates a safe space for employees to vent thoughts anonymously.']::text[], array['Woebot', 'Wysa', 'ChatGPT']::text[], false, true, 'en', 8),
  ('ai-generated-entertainment-activities', 'AI-Generated Entertainment and Activities', '#21', 'marketing', 'low', 'quality', 'Companies struggle to create engaging, unique content for family events or customer segments with children.', 'Gen AI creates personalized stories, interactive games, and creative tasks tailored to specific age groups and themes.', array['Increased customer loyalty through unique, personalized experiences for families.', 'Significant time savings in planning company events and workshops.', 'Ability to rapidly scale creative concepts across different platforms.']::text[], array['ChatGPT', 'Midjourney', 'StoryBird AI']::text[], false, true, 'en', 9),
  ('ai-powered-interview-preparation', 'AI-Powered Interview Preparation', '#11', 'hr', 'low', 'quality', 'Candidates and employees often feel unprepared and stressed before critical meetings, leading to underperformance.', 'Gen AI simulates realistic interview scenarios and provides instant feedback on answers, tone, and delivery.', array['Increased employee confidence before internal and external presentations.', 'Higher quality in candidate screening through better-prepared interviewers.', 'Reduction in stress-related errors during critical business calls.']::text[], array['ChatGPT Voice Mode', 'Claude', 'Interviewer.ai']::text[], false, true, 'en', 10),
  ('ai-powered-project-planning', 'AI-Powered Project Planning', '#20', 'operations', 'low', 'efficiency', 'Projects often fail due to unrealistic timelines and a lack of overview regarding sub-tasks.', 'Gen AI creates structured plans, milestones, and task lists based on high-level goals.', array['Faster transition from idea to executable plan.', 'Better identification of potential bottlenecks in the project flow.', 'Increased transparency and structure in team collaboration.']::text[], array['Asana Intelligence', 'ChatGPT', 'Monday.com AI']::text[], false, true, 'en', 11),
  ('ai-supported-wellbeing', 'AI-Supported Well-being and Health Promotion', '#10', 'hr', 'low', 'quality', 'Employee health and well-being are crucial for productivity, but personalized counseling is expensive and hard to scale.', 'Gen AI offers personalized health plans, nutritional guidance, and wellness tips based on each employee''s lifestyle and goals.', array['Reduced absenteeism through focus on preventive health.', 'Increased employee energy and focus throughout the workday.', 'A strong value-add to company benefits (Employer Branding).']::text[], array['MyFitnessPal (AI)', 'ChatGPT', 'Oura (AI insights)']::text[], false, true, 'en', 12),
  ('automated-generation-relevant-images', 'Automated Generation of Relevant Images', '#12', 'marketing', 'medium', 'efficiency', 'Companies spend too many resources on stock photos or expensive graphic processes for blogs and social media.', 'Gen AI creates unique, brand-specific images instantly based on text descriptions.', array['Drastic reduction in costs for stock photos and external designers.', 'Faster time-to-market for visual content in campaigns.', 'Unique visual identity without the risk of using the same images as competitors.']::text[], array['Midjourney', 'DALL-E 3', 'Canva Magic Design']::text[], false, true, 'en', 13),
  ('automated-legal-document-generation', 'Automated Legal Document Generation', '#28', 'operations', 'high', 'efficiency', 'Drafting standard contracts and legal documents is time-consuming and expensive in legal fees.', 'Gen AI generates customized legal drafts based on specific inputs, ensuring consistency and correct formatting.', array['Significant savings on legal costs for standardized tasks.', 'Faster turnaround time for contracts and agreements.', 'Reduction in human error through the use of precise templates.']::text[], array['Harvey AI', 'Ironclad', 'Spellbook']::text[], false, true, 'en', 14),
  ('boost-confidence-decision-making', 'Boost Confidence and Decision Making', '#18', 'operations', 'low', 'quality', 'Employee uncertainty leads to hesitation and lack of initiative in critical projects.', 'AI acts as a sparring partner that validates decisions, provides positive feedback, and offers new perspectives.', array['Faster decision-making processes by having an AI backup.', 'Increased risk-taking and innovation among employees.', 'Improved psychological safety through objective feedback and support.']::text[], array['ChatGPT', 'Pi', 'Claude']::text[], false, true, 'en', 15),
  ('corporate-llm-internal-copilot', 'Corporate LLM & Internal Copilot', '#22', 'it', 'high', 'efficiency', 'Employees are overwhelmed by internal data and spend too much time searching for answers in unstructured documents.', 'Implementation of a private corporate LLM that acts as an intelligent assistant across documents, support, and data analysis.', array['Radical improvement in employee productivity through quick access to internal knowledge.', 'Secure handling of sensitive data within the company''s own infrastructure.', 'Automation of routine support tasks and document generation.']::text[], array['Azure OpenAI', 'Microsoft Copilot', 'Custom LLM stack']::text[], false, true, 'en', 16),
  ('engagement-creative-content', 'Engagement Through Creative and Playful Content', '#7', 'marketing', 'low', 'quality', 'Static and boring content is ignored by customers, leading to low brand awareness and engagement.', 'Gen AI is used to create fun, humorous, and viral potential through memes, quirky scenarios, and creative play with the brand.', array['Higher social media engagement through relevant humor.', 'Humanizing the brand by showing personality and creativity.', 'Lower production costs for lightweight entertainment content.']::text[], array['Midjourney', 'Suno', 'ChatGPT']::text[], false, true, 'en', 17),
  ('exponential-ideation', 'Exponential Ideation and Conceptualization', '#6', 'marketing', 'low', 'growth', 'Creative stagnation in marketing and product development hampers innovation and competitiveness.', 'Gen AI acts as an infinite source of creative ideas, combining data patterns and trends into new concepts in seconds.', array['10x more ideas in less time during brainstorming sessions.', 'Faster identification of winning campaign concepts.', 'Low-cost experimentation with ''wildcard'' ideas without risk.']::text[], array['Claude.ai', 'Miro Assist', 'Midjourney']::text[], false, true, 'en', 18),
  ('hyper-personalized-learning', 'Hyper-Personalized Learning and Upskilling', '#4', 'hr', 'low', 'quality', 'Standardized courses often miss the mark on employee needs, wasting both time and resources.', 'Gen AI creates interactive learning content that adapts to individual styles, pace, and existing knowledge, making training much more effective.', array['Significantly faster upskilling of employees.', 'Reduced time spent on irrelevant training material.', 'Instant feedback loop ensuring correct learning from the start.']::text[], array['Learnai.nu Custom Tutor', 'Kajabi', 'ChatGPT Team']::text[], false, true, 'en', 19),
  ('hyper-specific-knowledge-search', 'Hyper-Specific Knowledge Search', '#13', 'operations', 'low', 'efficiency', 'Employees waste time searching for specific info in massive datasets or through imprecise web searches.', 'AI models synthesize information from multiple sources and provide direct answers to complex, technical questions.', array['Significant time savings when researching technical components or regulations.', 'Ability to identify objects or parts via image recognition in the field.', 'Faster decision-making based on precise information synthesis.']::text[], array['Perplexity AI', 'ChatGPT Search', 'Glean']::text[], false, true, 'en', 20),
  ('intelligent-anti-trolling-protection', 'Intelligent Anti-Trolling Protection', '#30', 'marketing', 'medium', 'quality', 'Online communities and social media can quickly be flooded by negativity and trolling, damaging the brand.', 'AI detects harmful comments in real-time and suggests moderation strategies or constructive counter-responses.', array['Protection of brand reputation through healthier online environments.', 'Savings on manual moderation and community management.', 'Better customer experience in the company''s digital channels.']::text[], array['OpenAI Moderation API', 'CleanSpeak', 'Perspective API']::text[], false, true, 'en', 21),
  ('intelligent-business-travel-planning', 'Intelligent Business Travel Planning', '#24', 'operations', 'low', 'efficiency', 'Planning complex business trips with multiple stops, meetings, and logistics is an administrative burden.', 'AI optimizes travel itineraries based on preferences, schedules, and budgets, delivering a fully optimized route plan.', array['Drastic reduction in time spent on travel administration.', 'Better optimization of time between meetings, increasing efficiency on the go.', 'Reduced travel costs through AI-identified price optimizations.']::text[], array['ChatGPT with Travel Plugins', 'Roam Around', 'Tripnotes']::text[], false, true, 'en', 22),
  ('intelligent-organizing-workday', 'Intelligent Organizing of Workday and Priorities', '#2', 'operations', 'low', 'efficiency', 'Many employees suffer from information overload and struggle to prioritize tasks, leading to stress and decreased productivity.', 'Gen AI acts as a personal operations assistant, analyzing task lists, deadlines, and goals to create an optimized schedule and structure both physical and digital work environments.', array['Increased output through better time management and elimination of time-wasters.', 'Reduced stress levels among employees due to clearer overviews.', 'Better alignment between daily tasks and overall strategic goals.']::text[], array['ChatGPT', 'Notion AI', 'Reclaim.ai']::text[], false, true, 'en', 23),
  ('optimization-codebase-refactoring', 'Optimization of Existing Codebase (Refactoring)', '#8', 'it', 'high', 'quality', 'Legacy code and technical debt make systems slow, insecure, and difficult to maintain.', 'Gen AI analyzes existing code to find bugs, optimize performance, and suggest modern alternatives, improving system stability.', array['Reduction of technical debt and maintenance costs.', 'Higher system security through automated bug detection.', 'Improved performance and speed in critical business systems.']::text[], array['GitHub Copilot', 'Cursor', 'SonarQube (AI features)']::text[], false, true, 'en', 24),
  ('personalized-learning-coaching', 'Personalized Learning and Coaching', '#17', 'hr', 'medium', 'quality', 'Traditional employee training is often one-size-fits-all and ineffective at closing specific skill gaps.', 'AI acts as a personal tutor, adapting teaching materials and difficulty to the individual employee.', array['Faster skill development through adaptive learning pathways.', '24/7 access to a patient tutor who never loses track of progress.', 'Increased knowledge retention through interactive quizzes and feedback.']::text[], array['Khanmigo', 'ChatGPT Personal Tutor', 'Coursera Coach']::text[], false, true, 'en', 25),
  ('purpose-driven-career-development', 'Purpose-Driven Career Development and Self-Reflection', '#3', 'hr', 'medium', 'quality', 'Lack of direction and purpose at work is a major driver of employee turnover and low engagement.', 'Using Gen AI, employees can undergo guided reflection processes that match their personal values with the company''s mission and career opportunities.', array['Higher employee retention through increased job satisfaction and meaning.', 'Better utilization of employees'' hidden talents and passions.', 'Strengthened company culture based on shared values.']::text[], array['Claude.ai', 'ChatGPT', 'Mindgrasp']::text[], false, true, 'en', 26),
  ('resource-optimization-cook-with-what-you-have', 'Resource Optimization: Cook with what you have', '#15', 'operations', 'low', 'efficiency', 'Waste of existing resources or inventory due to a lack of overview regarding potential uses.', 'AI suggests creative solutions or recipes based solely on available inputs and ingredients.', array['Reduction of food waste in canteens and the hospitality industry.', 'Optimized use of existing inventory before new purchases.', 'Creative problem solving in logistics by maximizing available means.']::text[], array['ChatGPT Vision', 'Chef GPT', 'Custom GPTs']::text[], false, true, 'en', 27),
  ('simple-explainers-complex-docs', 'Simple Explainers for Complex Docs', '#14', 'operations', 'medium', 'quality', 'Technical manuals and API documentation are often incomprehensible to non-experts, creating bottlenecks.', 'Gen AI breaks down complex knowledge into easily digestible explanations (ELI5) tailored to the audience.', array['Frees up specialist time by letting AI answer basic technical queries.', 'Improved customer service through faster understanding of complex cases.', 'Faster onboarding of new employees into complex systems.']::text[], array['ChatPDF', 'NotebookLM', 'ChatGPT']::text[], false, true, 'en', 28),
  ('strategic-sparring-deep-dialogues', 'Strategic Sparring and Deep Dialogues', '#29', 'hr', 'medium', 'quality', 'Leaders and specialists often lack a confidential partner to explore complex thoughts and strategic dilemmas.', 'AI facilitates reflective dialogues by asking challenging questions and providing new insights in a safe environment.', array['Strengthened leadership through deeper reflection and self-awareness.', 'Innovative solutions to complex business challenges.', 'Increased mental clarity for key employees.']::text[], array['Pi', 'ChatGPT Plus', 'Claude']::text[], false, true, 'en', 29),
  ('strategic-tone-of-voice-adjustment', 'Strategic Tone-of-Voice Adjustment', '#19', 'marketing', 'low', 'quality', 'Emails and communications can often be misunderstood as confrontational or unclear, damaging relationships.', 'AI analyzes and rewrites text to hit the precise desired tone (professional, friendly, empathetic).', array['Fewer conflicts in internal and external correspondence.', 'Ensures company brand voice is maintained by everyone.', 'More effective communication to culturally diverse recipients.']::text[], array['Grammarly Business', 'Jasper', 'ChatGPT']::text[], false, true, 'en', 30)
on conflict (slug, locale) do nothing;

insert into public.resources (slug, title, type, url, description, rating, topics, content_language, published, locale, sort_order) values
  ('ai-first-the-playbook-for-a-future-proof-business-and-brand', 'AI First: The Playbook for a Future-Proof Business and Brand', 'bog', 'https://www.amazon.de/-/da/AI-First-Playbook-Future-Proof-Business/dp/1647829658/', 'Af Adam Brotman og Andy Sack. En praktisk guide til at fremtidssikre din virksomhed og dit brand med AI-first strategier.', null, array['Strategi', 'Business', 'Branding']::text[], 'da', true, 'da', 0),
  ('co-intelligence-living-and-working-with-ai', 'Co-Intelligence: Living and Working with AI', 'bog', 'https://www.amazon.de/-/da/Co-Intelligence-Definitive-Bestselling-Living-Working/dp/0753560771/', 'Af Ethan Mollick (Wharton professor). Den definitive guide til at leve og arbejde med AI i den nye æra af generativ kunstig intelligens.', null, array['Generativ AI', 'Produktivitet', 'Fremtiden']::text[], 'da', true, 'da', 1),
  ('rewired-the-mckinsey-guide-to-outcompeting-in-the-age-of-digital-and-ai', 'Rewired: The McKinsey Guide to Outcompeting in the Age of Digital and AI', 'bog', 'https://www.amazon.de/-/da/dp/1394381905', 'McKinsey-guide til digital transformation og hvordan virksomheder kan udkonkurrere i den digitale og AI-drevne tidsalder.', null, array['Digital transformation', 'McKinsey', 'Konkurrenceevne']::text[], 'da', true, 'da', 2),
  ('the-ai-driven-leader', 'The AI-Driven Leader', 'bog', 'https://www.amazon.de/-/da/Geoff-Woods/dp/B0GHYX8ZSM/', 'Af Geoff Woods. Lær hvordan du som leder kan udnytte AI til at træffe hurtigere og smartere beslutninger.', null, array['Ledelse', 'Beslutningstagning', 'AI-strategi']::text[], 'da', true, 'da', 3),
  ('56k', '56k', 'podcast', 'https://56kpodcast.dk/', 'Podcasten 56k giver dig Internettet på 30 minutter. Værterne Mads Viktor og Morten Saxnæs finder de bedste og mest saftige historier på Internettet og serverer dem i et skarpt og underholdende format.', 4.7, array['AI', 'teknologi', 'internetkultur', 'podcast']::text[], 'da', true, 'da', 4),
  ('ai-denmark', 'AI Denmark', 'podcast', 'https://open.spotify.com/show/3F2blLpAxsYnjRFsAx35jh', 'En podcast om kunstig intelligens set med danske briller.', null, array['AI', 'Danmark']::text[], 'da', true, 'da', 5),
  ('ai-for-alle', 'AI for alle', 'podcast', 'https://open.spotify.com/show/4tkjEEAMAHLIcscKtVHXpd', 'Podcasten er en del af AI for Alle - DIs strategiske indsats for at hjælpe danske virksomheder til at vinde med AI. Hver episode handler om et praktisk eksempel fra en af de mange AI-frontløbere i dansk erhvervsliv.', null, array['Business', 'DI', 'Case Studies']::text[], 'da', true, 'da', 6),
  ('ai-mennesker', 'AI Mennesker', 'podcast', 'https://open.spotify.com/show/76dGmnRMuRmahvDQGA4Rpc', 'Generativ AI vil forandre vores verden inden for få år. Spørgsmålet er hvad du vil gøre ved det? Techjournalist- og foredragsholder David Guldager dykker ned i hvad generativ AI er og hvordan det bliver brugt derude.', null, array['Generativ AI', 'Interviews']::text[], 'da', true, 'da', 7),
  ('ai-revolutionen', 'AI Revolutionen', 'podcast', 'https://open.spotify.com/show/1UaRk75DRUCN3bOT2tvSac', 'Velkommen til AI Revolutionen! Vi står midt i en ny tid, hvor ChatGPT, Grok, DeepSeek og selvkørende biler er ved at overtage kloden. Lyt med når vi dykker ned i de spændende AI-nyheder.', null, array['Tech News', 'AI Nyheder']::text[], 'da', true, 'da', 8),
  ('dataklubben', 'Dataklubben', 'podcast', 'https://open.spotify.com/show/4qlj4Uwh0CgZlTlDe0kHhv', 'Dataklubben er podcasten til dig med passion for data, analytics, digitalisering og transformation. Vi inviterer dig tæt på de entusiaster, som tør tale om ambitioner og dele de erfaringer, som skabte resultater.', null, array['Data', 'Analytics', 'Digitalisering']::text[], 'da', true, 'da', 9),
  ('edb-5-0', 'EDB 5.0', 'podcast', 'https://open.spotify.com/show/0JT4dvTrCJEzJjk0elBJDl', 'EDB 5.0 er en dansk teknologi podcast med fokus på kunstig intelligens og intelligent automatisering. Vi taler med landets førende virksomheder om kunstig intelligens, intelligent automation, data og data-etik.', null, array['Tech', 'Automation', 'Data-etik']::text[], 'da', true, 'da', 10),
  ('kpmg-tech-talk', 'KPMG Tech Talk', 'podcast', 'https://podcasts.apple.com/dk/podcast/kpmg-tech-talk/id1610516314', 'Podcastserie hvor førende erhvervsfolk og forskere taler om fremtidens teknologier - og de teknologier, du kan bruge allerede i dag.', null, array['Business', 'KPMG', 'Teknologi']::text[], 'da', true, 'da', 11),
  ('maskinstorm', 'Maskinstorm', 'podcast', 'https://open.spotify.com/show/7B7DBIlrIvH8j8lZdWdzIz', 'Hvordan vil kunstig intelligens forandre vores verden? I podcasten Maskinstorm inviterer Dagbladet Information eksperter i studiet for at forsøge at finde svar på netop det spørgsmål.', null, array['Society', 'Tech', 'Information']::text[], 'da', true, 'da', 12),
  ('prompt', 'Prompt', 'podcast', 'https://open.spotify.com/show/4yl5gZBKQWO3ap4r6Lrqqq', 'Hver uge går Prompt bag om tech-giganternes ''Ultra Pro Max''-løfter, bullshit-tester de nyeste tech-trends og spørger, om kunstig intelligens og AI er vores ven eller fjende. Sammen med tech-korrespondent Henrik Moltke nærlæser tech-analytiker Marcel Mirzaei-Fard de største historier om den teknologiske udvikling, der forandrer vores verden og muligheder.', null, array['Tech News', 'DR']::text[], 'da', true, 'da', 13),
  ('ai-explained', 'AI Explained', 'youtube', 'https://www.youtube.com/@aiexplained-official', 'Dybdegående analyser og forklaringer af de nyeste AI-modeller, forskningsartikler og teknologiske gennembrud. Kanalen fokuserer på at gøre komplekse AI-koncepter forståelige for alle.', null, array['AI-forskning', 'Maskinlæring', 'AI-modeller']::text[], 'da', true, 'da', 14),
  ('akm', 'AKM', 'youtube', 'https://www.youtube.com/@AKMofficial', 'AI-nyheder, produktanmeldelser og praktiske tips til at bruge kunstig intelligens i hverdagen.', null, array['AI-nyheder', 'Produktanmeldelser', 'AI-tips']::text[], 'da', true, 'da', 15),
  ('all-about-ai', 'All About AI', 'youtube', 'https://www.youtube.com/@AllAboutAI', 'Praktiske tutorials og guides til AI-værktøjer og workflows med fokus på hands-on anvendelse.', null, array['AI-tutorials', 'Praktiske guides', 'AI-workflows']::text[], 'da', true, 'da', 16),
  ('ibm-technology', 'IBM Technology', 'youtube', 'https://www.youtube.com/@IBMTechnology', 'Tekniske forklaringer af AI, cloud computing og enterprise-teknologi fra IBM eksperter.', null, array['Enterprise AI', 'Cloud Computing', 'Teknologi']::text[], 'da', true, 'da', 17),
  ('machine-learning-street-talk', 'Machine Learning Street Talk', 'youtube', 'https://www.youtube.com/@MachineLearningStreetTalk', 'Dybdegående samtaler med førende AI-forskere om machine learning, AGI og fremtiden for AI.', null, array['AI-forskning', 'Machine Learning', 'AGI']::text[], 'da', true, 'da', 18),
  ('matt-wolfe-mreflow', 'Matt Wolfe (mreflow)', 'youtube', 'https://www.youtube.com/@mreflow', 'Matt Wolfe dækker de nyeste AI-værktøjer, nyheder og automatiseringer. Han driver også FutureTools.io, en populær database med AI-værktøjer. Fantastisk kanal for at holde sig opdateret med AI-udviklingen.', null, array['AI-værktøjer', 'Automatisering', 'AI-nyheder']::text[], 'da', true, 'da', 19),
  ('openai', 'OpenAI', 'youtube', 'https://www.youtube.com/@OpenAI', 'Den officielle YouTube-kanal fra OpenAI, skaberne af ChatGPT, GPT-5 og DALL-E. Her finder du produktlanceringer, forskningspræsentationer og demoer af deres seneste AI-teknologier.', null, array['ChatGPT', 'GPT-5', 'AI-forskning']::text[], 'da', true, 'da', 20),
  ('skill-leap-ai', 'Skill Leap AI', 'youtube', 'https://www.youtube.com/@SkillLeapAI', 'Begyndervenlige tutorials til AI-værktøjer som ChatGPT, Midjourney og andre populære platforme.', null, array['AI-tutorials', 'Begynderguides', 'ChatGPT']::text[], 'da', true, 'da', 21),
  ('ai-first-the-playbook-for-a-future-proof-business-and-brand', 'AI First: The Playbook for a Future-Proof Business and Brand', 'bog', 'https://www.amazon.de/-/da/AI-First-Playbook-Future-Proof-Business/dp/1647829658/', 'By Adam Brotman and Andy Sack. A practical guide to future-proofing your business and brand with AI-first strategies.', null, array['Strategy', 'Business', 'Branding']::text[], 'en', true, 'en', 0),
  ('co-intelligence-living-and-working-with-ai', 'Co-Intelligence: Living and Working with AI', 'bog', 'https://www.amazon.de/-/da/Co-Intelligence-Definitive-Bestselling-Living-Working/dp/0753560771/', 'By Ethan Mollick (Wharton professor). The definitive playbook for working, learning, and living in the new age of AI.', null, array['Generative AI', 'Productivity', 'Future of Work']::text[], 'en', true, 'en', 1),
  ('rewired-the-mckinsey-guide-to-outcompeting-in-the-age-of-digital-and-ai', 'Rewired: The McKinsey Guide to Outcompeting in the Age of Digital and AI', 'bog', 'https://www.amazon.de/-/da/dp/1394381905', 'The McKinsey guide to digital transformation and how businesses can outcompete in the age of digital and AI.', null, array['Digital Transformation', 'McKinsey', 'Competition']::text[], 'en', true, 'en', 2),
  ('the-ai-driven-leader', 'The AI-Driven Leader', 'bog', 'https://www.amazon.de/-/da/Geoff-Woods/dp/B0GHYX8ZSM/', 'By Geoff Woods. Learn how to harness AI to make faster, smarter decisions as a leader.', null, array['Leadership', 'Decision Making', 'AI Strategy']::text[], 'en', true, 'en', 3),
  ('56k', '56k', 'podcast', 'https://56kpodcast.dk/', 'The 56k podcast gives you the internet in 30 minutes. Hosts Mads Viktor and Morten Saxnæs find the sharpest, funniest, and most important stories online and deliver them in a concise, entertaining format.', 4.7, array['AI', 'teknologi', 'internetkultur', 'podcast']::text[], 'da', true, 'en', 4),
  ('ai-at-scale', 'AI at Scale', 'podcast', 'https://open.spotify.com/show/5P9EbPHVYSyBUR5wZDY9Wz', 'The Schneider Electric AI at Scale podcast invites AI practitioners and experts to share their experiences, challenges, and AI success stories. How do I implement AI successfully and sustainably?', null, array['Business', 'Enterprise AI', 'Schneider Electric']::text[], 'en', true, 'en', 5),
  ('ai-in-action', 'AI in Action', 'podcast', 'https://open.spotify.com/show/1Up5zsC8ZwujnDK6cTDuEO', 'AI in Action explores what it takes to put artificial intelligence into action across a rapidly evolving business and tech landscape. Each episode focuses on responsible AI implementation and real-world business challenges.', null, array['Business', 'IBM', 'Responsible AI']::text[], 'en', true, 'en', 6),
  ('ai-that-means-business', 'AI That Means Business', 'podcast', 'https://open.spotify.com/show/3n9ymmwtYMtdFUfzk0kqaw', 'What''s next for artificial intelligence? And how are companies putting it to work in the here and now? Join Google experts for a deep dive into the technology that''s changing the world of business.', null, array['Business', 'WSJ', 'Google']::text[], 'en', true, 'en', 7),
  ('ai-with-allie', 'AI with ALLIE', 'podcast', 'https://open.spotify.com/show/1qk1WscvoxBIhvZb15eERp', 'Join Allie K. Miller, the #1 most followed voice in AI business with over 1.5 million followers, as she simplifies AI and tech into practical, easy-to-understand strategies anyone can use—no coding required.', null, array['Tech', 'Business Strategy', 'LLMs']::text[], 'en', true, 'en', 8),
  ('beyond-the-prompt', 'Beyond the Prompt', 'podcast', 'https://open.spotify.com/show/2TnArU2YYSi1vdfEcoK1Qh', 'Beyond the Prompt dives deep into the world of AI and its expanding impact on business and daily work. Hosted by Jeremy Utley of Stanford''s d.school and Henrik Werdelin, featuring conversations with innovators and leaders.', null, array['Business', 'Stanford', 'Innovation']::text[], 'en', true, 'en', 9),
  ('google-deepmind-the-podcast', 'Google DeepMind: The Podcast', 'podcast', 'https://open.spotify.com/show/39fjU5Q5L5UecTCRMeqjwb', 'What is generative AI? How do you create safe and capable models? Join Professor Hannah Fry as she goes behind the scenes of the world-leading research lab to uncover the extraordinary ways AI is transforming our world.', null, array['Research', 'Google', 'DeepMind']::text[], 'en', true, 'en', 10),
  ('me-myself-and-ai', 'Me, Myself, and AI', 'podcast', 'https://open.spotify.com/show/7ysPBcYtOPVgI6W5an6lup', 'Why do only 10% of companies succeed with AI? In this series by MIT SMR and BCG, we talk to the leaders who''ve achieved big wins with AI in their companies and learn how they did it.', null, array['Business', 'MIT', 'BCG']::text[], 'en', true, 'en', 11),
  ('nvidia-ai-podcast', 'NVIDIA AI Podcast', 'podcast', 'https://open.spotify.com/show/4TB4pnynaiZ6YHoKmyVN0L', 'One person, one interview, one story. Join us as we explore the impact of AI on our world, one amazing person at a time. Every week, we''ll bring you another tale as we build a real-time oral history of AI.', null, array['Tech', 'Research', 'NVIDIA']::text[], 'en', true, 'en', 12),
  ('techtalks-new-tech-frontiers', 'TECHTalks New Tech Frontiers', 'podcast', 'https://open.spotify.com/show/2mZsMgB8tqDtiE6wk3rSVH', 'TECHTalks brings a great variety of topics and guests on next-generation technologies to help everyone better learn how they could intersect with their work and lives today and in the future.', null, array['Technology', 'Deloitte', 'Innovation']::text[], 'en', true, 'en', 13),
  ('ai-explained', 'AI Explained', 'youtube', 'https://www.youtube.com/@aiexplained-official', 'In-depth analyses and explanations of the latest AI models, research papers, and technological breakthroughs. The channel focuses on making complex AI concepts understandable for everyone.', null, array['AI Research', 'Machine Learning', 'AI Models']::text[], 'en', true, 'en', 14),
  ('akm', 'AKM', 'youtube', 'https://www.youtube.com/@AKMofficial', 'AI news, product reviews, and practical tips for using artificial intelligence in everyday life.', null, array['AI News', 'Product Reviews', 'AI Tips']::text[], 'en', true, 'en', 15),
  ('all-about-ai', 'All About AI', 'youtube', 'https://www.youtube.com/@AllAboutAI', 'Practical tutorials and guides for AI tools and workflows with a focus on hands-on application.', null, array['AI Tutorials', 'Practical Guides', 'AI Workflows']::text[], 'en', true, 'en', 16),
  ('ibm-technology', 'IBM Technology', 'youtube', 'https://www.youtube.com/@IBMTechnology', 'Technical explanations of AI, cloud computing, and enterprise technology from IBM experts.', null, array['Enterprise AI', 'Cloud Computing', 'Technology']::text[], 'en', true, 'en', 17),
  ('machine-learning-street-talk', 'Machine Learning Street Talk', 'youtube', 'https://www.youtube.com/@MachineLearningStreetTalk', 'In-depth conversations with leading AI researchers about machine learning, AGI, and the future of AI.', null, array['AI Research', 'Machine Learning', 'AGI']::text[], 'en', true, 'en', 18),
  ('matt-wolfe-mreflow', 'Matt Wolfe (mreflow)', 'youtube', 'https://www.youtube.com/@mreflow', 'Matt Wolfe covers the latest AI tools, news, and automations. He also runs FutureTools.io, a popular database of AI tools. Great channel for staying up-to-date with AI developments.', null, array['AI Tools', 'Automation', 'AI News']::text[], 'en', true, 'en', 19),
  ('openai', 'OpenAI', 'youtube', 'https://www.youtube.com/@OpenAI', 'The official YouTube channel from OpenAI, creators of ChatGPT, GPT-5, and DALL-E. Here you''ll find product launches, research presentations, and demos of their latest AI technologies.', null, array['ChatGPT', 'GPT-5', 'AI Research']::text[], 'en', true, 'en', 20),
  ('skill-leap-ai', 'Skill Leap AI', 'youtube', 'https://www.youtube.com/@SkillLeapAI', 'Beginner-friendly tutorials for AI tools like ChatGPT, Midjourney, and other popular platforms.', null, array['AI Tutorials', 'Beginner Guides', 'ChatGPT']::text[], 'en', true, 'en', 21)
on conflict (slug, locale) do nothing;

insert into public.events (slug, title, description, event_date, time_start, time_end, location_type, location_name, registration_url, organizer, price, published, locale, sort_order) values
  ('agent-in-a-day-2026', 'Agent in a Day - Microsoft Copilot Studio', 'Lær at bygge AI-agenter med Microsoft Copilot Studio på én dag. Hands-on workshop for både forretningseksperter og IT-udviklere. I samarbejde med Context&.', '2026-02-24T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'København', 'https://msevents.microsoft.com/event?id=3962955086', 'Microsoft & Context&', 0, true, 'da', 0),
  ('app-in-a-day-2026', 'App in a Day - Power Apps Workshop', 'Lær at bygge forretningsapplikationer uden kode med Microsoft Power Platform. Heldags hands-on workshop i samarbejde med Abakion.', '2026-03-10T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'København', 'https://msevents.microsoft.com/event?id=4035673089', 'Microsoft & Abakion', 0, true, 'da', 1),
  ('ai-marketing-conference-2026', 'AI Marketing Conference 2026', 'Danmarks største AI-konference for marketing. Hands-on frameworks, tools og danske cases til dig, der vil implementere AI i marketing og forretningen.', '2026-03-12T00:00:00+00:00', null, null, 'fysisk', 'København', 'https://www.ai-marketingconference.dk/billetter', 'Obsidian', null, true, 'da', 2),
  ('microsoft-ai-tour-copenhagen-2026', 'Microsoft AI Tour Copenhagen', 'Gratis heldagsevent om AI-innovation fra Microsoft. Oplev keynotes, breakout sessions, live demos og netværk med eksperter på Lokomotivværkstedet.', '2026-03-26T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Lokomotivværkstedet, København', 'https://aitour.microsoft.com/flow/microsoft/copenhagen26/landingpage/page/cityhome', 'Microsoft', 0, true, 'da', 3),
  ('ai-data-day-2026', 'AI & Data Day 2026', 'Konference om AI og data hos Villa Copenhagen. Oplev de seneste trends og cases inden for kunstig intelligens og dataanalyse.', '2026-05-07T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Villa Copenhagen', 'https://dataday.dk/', 'Inspari / Valantic', null, true, 'da', 4),
  ('driving-ai-2026', 'Driving AI 2026', 'Hør sidste nyt på AI-fronten - case-studier, de nyeste modeller og faglige tricks. For både AI-professionelle og nysgerrige. Arrangeret af IDA.', '2026-05-27T00:00:00+00:00', '08:30', '18:00', 'fysisk', 'IDA Conference, Kalvebod Brygge, København', 'https://ida.dk/driving-ai', 'IDA', null, true, 'da', 5),
  ('danish-digital-award-2026', 'Danish Digital Award 2026', 'Landets bedste digitale marketingarbejde bliver fejret med et stort anlagt show. Oplev vinderne af årets bedste digitale projekter.', '2026-06-03T00:00:00+00:00', '18:00', '23:00', 'fysisk', 'København', 'https://danishdigitalaward.dk/', 'Markedsføring', null, true, 'da', 6),
  ('future-product-days-2026', 'Future Product Days 2026', 'Konference for produktledere og designere. Tre dage med sessions om Product Design & UX, Engineering & Technology, Management & Strategy og Personal Skills & Growth.', '2026-09-22T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'København', 'https://www.futureproductdays.com/program', 'Future Product Days', null, true, 'da', 7),
  ('agent-in-a-day-2026', 'Agent in a Day - Microsoft Copilot Studio', 'Learn to build AI agents with Microsoft Copilot Studio in one day. Hands-on workshop for both business experts and IT developers. In partnership with Context&.', '2026-02-24T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Copenhagen', 'https://msevents.microsoft.com/event?id=3962955086', 'Microsoft & Context&', 0, true, 'en', 0),
  ('app-in-a-day-2026', 'App in a Day - Power Apps Workshop', 'Learn to build business applications without code using Microsoft Power Platform. Full-day hands-on workshop in partnership with Abakion.', '2026-03-10T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Copenhagen', 'https://msevents.microsoft.com/event?id=4035673089', 'Microsoft & Abakion', 0, true, 'en', 1),
  ('ai-marketing-conference-2026', 'AI Marketing Conference 2026', 'Denmark''s largest AI conference for marketing. Hands-on frameworks, tools, and Danish cases for those who want to implement AI in marketing and business.', '2026-03-12T00:00:00+00:00', null, null, 'fysisk', 'Copenhagen', 'https://www.ai-marketingconference.dk/billetter', 'Obsidian', null, true, 'en', 2),
  ('microsoft-ai-tour-copenhagen-2026', 'Microsoft AI Tour Copenhagen', 'Free full-day AI innovation event from Microsoft. Experience keynotes, breakout sessions, live demos and network with experts at Lokomotivværkstedet.', '2026-03-26T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Lokomotivværkstedet, Copenhagen', 'https://aitour.microsoft.com/flow/microsoft/copenhagen26/landingpage/page/cityhome', 'Microsoft', 0, true, 'en', 3),
  ('ai-data-day-2026', 'AI & Data Day 2026', 'Conference on AI and data at Villa Copenhagen. Experience the latest trends and cases in artificial intelligence and data analytics.', '2026-05-07T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Villa Copenhagen', 'https://dataday.dk/', 'Inspari / Valantic', null, true, 'en', 4),
  ('driving-ai-2026', 'Driving AI 2026', 'Hear the latest AI news - case studies, the newest models and professional tips. For both AI professionals and the curious. Organized by IDA.', '2026-05-27T00:00:00+00:00', '08:30', '18:00', 'fysisk', 'IDA Conference, Kalvebod Brygge, Copenhagen', 'https://ida.dk/driving-ai', 'IDA', null, true, 'en', 5),
  ('danish-digital-award-2026', 'Danish Digital Award 2026', 'Denmark''s best digital marketing work is celebrated with a grand show. Experience the winners of the year''s best digital projects.', '2026-06-03T00:00:00+00:00', '18:00', '23:00', 'fysisk', 'Copenhagen', 'https://danishdigitalaward.dk/', 'Markedsføring', null, true, 'en', 6),
  ('future-product-days-2026', 'Future Product Days 2026', 'Conference for product managers and designers. Three days of sessions on Product Design & UX, Engineering & Technology, Management & Strategy and Personal Skills & Growth.', '2026-09-22T00:00:00+00:00', '09:00', '17:00', 'fysisk', 'Copenhagen', 'https://www.futureproductdays.com/program', 'Future Product Days', null, true, 'en', 7)
on conflict (slug, locale) do nothing;
